import * as dotenv from 'dotenv';
dotenv.config();

export const config = {
    DB_PATH: process.env.DB_PATH,
    PORT:process.env.PORT,
    JWT_SECRET: process.env.JWT_SECRET,
    FIREBASE_ADMIN_TYPE: process.env.FIREBASE_ADMIN_TYPE,
    FIREBASE_ADMIN_PROJECT_ID: process.env.FIREBASE_ADMIN_PROJECT_ID,
    FIREBASE_ADMIN_PRIVATE_KEY_ID: process.env.FIREBASE_ADMIN_PRIVATE_KEY_ID,
    FIREBASE_ADMIN_PRIVATE_KEY: process.env.FIREBASE_ADMIN_PRIVATE_KEY,
    FIREBASE_ADMIN_CLIENT_EMAIL: process.env.FIREBASE_ADMIN_CLIENT_EMAIL,
    FIREBASE_ADMIN_CLIENT_ID: process.env.FIREBASE_ADMIN_CLIENT_ID,
    FIREBASE_ADMIN_AUTH_URI: process.env.FIREBASE_ADMIN_AUTH_URI,
    FIREBASE_ADMIN_TOKEN_URI: process.env.FIREBASE_ADMIN_TOKEN_URI,
    FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL: process.env.FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL,
    FIREBASE_ADMIN_CLIENT_X509_CERT_URL: process.env.FIREBASE_ADMIN_CLIENT_X509_CERT_URL,
    FIREBASE_USER_API_KEY: process.env.FIREBASE_USER_API_KEY,
    FIREBASE_USER_AUTH_DOMAIN: process.env.FIREBASE_USER_AUTH_DOMAIN,
    FIREBASE_USER_PROJECT_ID: process.env.FIREBASE_USER_PROJECT_ID,
    FIREBASE_USER_STROAGE_BUCKET: process.env.FIREBASE_USER_STROAGE_BUCKET,
    FIREBASE_USER_MESSAGING_SENDER_ID: process.env.FIREBASE_USER_MESSAGING_SENDER_ID,
    FIREBASE_USER_APP_ID: process.env.FIREBASE_USER_APP_ID,
}